### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by Bartvds** [w-m/pleonasm#1]
I saw you post on reddit and I think I have a use case where this could be useful (or at least interesting to try).

I'm building a node.js based CLI-tool that depends heavily on the Github API so there are a lot of sha1-hashes in the system. Just like most git tools I shorten the 40 hex chars to like 6 or 8 for readability, but maybe it'd be cool to also show these human-friendly strings.

So maybe you could publish pleonasm to npm when it reaches a usable state?

**Comment by w-m** [comment]
Good idea, I'd very much like to see someone play around with it. So I will add a proper README shortly and then go for node.js / publishing to npm.

**Comment by w-m** [comment]
Just published pleonasm to npm, with the tests working in node.js as well, so just try it out:

```
npm install pleonasm
npm test pleonasm
```

I don't have any previous experience with node/npm, so please let me know if anything is amiss.

**Comment by Bartvds** [comment]
Was that name still free? Amazing :)

Published module looks good to me, works as expected, nice API too.

Only thing missing is linking travis-c (and some badges):

https://travis-ci.org/ (you want this)
http://badge.fury.io/ (handy to see published version and navigate to npm)

I'll let you know if I got some interesting results using it.

**Comment by Bartvds** [comment]
I have some feedback on the node.js module: I'll just put it here for  your consideration:

Maybe there should be something done to the way the module starts: in it's current form it is an odd mix between a module and a loader: we `require()` it as a regular (synchronous) module, but then still wait for a callback.

I think it should either implicitly synchronously load the dictionaries, or it might be better to explicitly call a `pleonasm.load(callback)` for an asynchronous start. Right now it looks out-of-place with the rest of the code (no other modules I know of do a require with a completion callback like that). It'd have to be safe for race-conditions of course (if you require/load it twice it should load only once but still notify all listeners).

For the asyncronous dictionary load you could look into using node's streams (grab a line-reader-stream from npm) and build the data structure while it is loading. Not essential, but could be smooth.

I've hackisly tried it in my project (using github api data) and it is amazing with 6-char sha hashes. Some of the phrases are funny, mystifying or sound like codenames for military operations.
