### ISSUE TITLE
Curate dictionary words

### ISSUE THREAD

**Issue by Bartvds** [w-m/pleonasm#3]
There are some words in the dictionary that could result in potentially offensive phrases. I'll edit this ticket if I find out more:

```
noah
jews
afrikaner
```

Also if this project pick up you _have_ to add a page to your site where people can share inputs string with hilarious output :smile:

**Comment by w-m** [comment]
I haven't made up my mind completely about this. Words come unfiltered out of a dictionary, currently. There are offensive words, but they are equally offensive against everyone. Like a chimpanzee with a typewriter.

If I stepped in and started curating, it would get unbalanced. There's no way to filter out all offensive things anyhow, as you can be offensive with a combination of the sweetest words.

Outright profane words might be another story, they'll have to go. I'll look around for a good reference list to remove them from the dictionary.

**Comment by Bartvds** [comment]
I agree with most of this personally.

It is just that some words are very likely to cause fuss. Doing anything at all with labels of religions can be a bit over-sensitive on the global internet. 

Races are a notch lower on the scale I guess, as long as they are not slurs.
